- name: Demo on using variables on playbooks  
  hosts: all 
  vars: 
    URL: play.google.com
  tasks:
    - name: Printing value of the variable
      ansible.builtin.debug:
        msg: Value of URL is {{ URL }}

    - name: Printing value of the variable which is not declared
      ansible.builtin.debug:
        msg: Name Of the car is {{ CARNAME }}


