- name: Installing Python on {{COMPONENT}}-{{ENV}}
  ansible.builtin.yum:
    name:
      - python36  
      - gcc
      - python3-devel
    state: present

- name: Creating App User 
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and extracting {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download




# - name: Ensure SELinux is set to enforcing mode
#   ansible.builtin.lineinfile:
#     path: /etc/selinux/config
#     regexp: '^SELINUX='
#     line: SELINUX=enforcing

# - name: Configuring Service
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: config_svc    

# - name: Configuring Node Name Repo 
#   ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}